#!/bin/bash

notify_title="Закон против транслюдей 🏳️‍⚧️"
notify_body="Дней с принятия закона против существования трансгендерных людей: "
notify_icon="dialog-error"
notify_id=$(cat "$(dirname -- "$0")/notify-ids" | grep -oP "${0##*/} \K([\d]+)")

days_from()
{
    echo $(( ($(date +%s) - $(date -d $1 +%s)) / (60 * 60 * 24) ))
}

antiTRANSlaw_date=20230724

days=$(days_from $antiTRANSlaw_date)

notify-send -u critical -r $notify_id -i "$notify_icon" "$notify_title" "$notify_body$days"
