#!/bin/bash

notify_title="Закон против ЛГБТ 🏳️‍🌈"
notify_body="Дней с принятия закона против ЛГБТ: "
notify_icon="dialog-error"
notify_id=$(cat "$(dirname -- "$0")/notify-ids" | grep -oP "${0##*/} \K([\d]+)")

days_from()
{
    echo $(( ($(date +%s) - $(date -d $1 +%s)) / (60 * 60 * 24) ))
}

antiLGBTlaw_date=20221205

days=$(days_from $antiLGBTlaw_date)

notify-send -u critical -r $notify_id -i "$notify_icon" "$notify_title" "$notify_body$days"
