#!/bin/bash

# Скрипт для экспоненциального изменения яркости

# Предварительные танцы с бубном для решения проблемы с падающей яркостью тут:
# https://forums.linuxmint.com/viewtopic.php?t=138760

current_level_file="/tmp/brightness-levels"
max_brightness=100
min_brightness=0

notify_title="Яркость"
notify_body="Текущая яркость экрана"
notify_icon="xfpm-brightness-lcd"
notify_id=$(cat "$HOME/.local/scripts/notify-ids" | grep -oP "${0##*/} \K([\d]+)" || echo 0)

# Создание дефолтного файла-конфигурации с 10 шагами
[[ ! -f $current_level_file ]] && levels 10

# Получить текущую яркость, возвращает число от 0 до 255
get() {
    light -G
}

# Установить текущую яркость, аргументы: число от 0 до 255
set() {
    light -S $1
}

# Увеличить яркость на один шаг
inc() {
    steps=($(cat $current_level_file))
    [[ ${steps[0]} -lt $(( ${#steps[@]} - 1 )) ]] && steps[0]=$(( ${steps[0]} + 1 ))
    echo ${steps[@]} > $current_level_file
    set ${steps[${steps[0]}]}
    notify ${steps[0]} $(( ${#steps[@]} - 1 ))
}

# Уменьшить яркость на один шаг
dec() {
    steps=($(cat $current_level_file))
    [[ ${steps[0]} -gt 1 ]] && steps[0]=$(( ${steps[0]} - 1 ))
    echo ${steps[@]} > $current_level_file
    set ${steps[${steps[0]}]}
    notify ${steps[0]} $(( ${#steps[@]} - 1 ))
}

# Послать уведомление об изменении яркости
notify() {
    level=$(( $1 * 100 / $2 ))
    notify-send -u low -r $notify_id -i "$notify_icon" "$notify_title" "$notify_body$current_layout" -h int:value:$level
}

# Установить количество шагов, аргументы: целое положительное число (в разумных пределах, т.е. до 255)
levels() {
    steps=($(python - << EOF
import sys
steps = $1 - 1
step = $(($max_brightness + 1)) ** (1 / steps)
levels = [0]
for n in range(steps):
    level = round(step ** (n + 1)) - 1
    level += max(0, levels[-1] - level + 1)
    levels.append(min(level, $max_brightness))
print(' '.join(map(str, levels[:$(($max_brightness + 1))])))
EOF
    ))

    steps=(${#steps[@]} ${steps[@]})
    echo ${steps[@]} > $current_level_file
    set ${steps[${steps[0]}]}
}

case $1 in
    "get")
        get
        ;;
    "set")
        set "${@:2}"
        ;;
    "inc")
        inc
        ;;
    "dec")
        dec
        ;;
    "levels")
        levels "${@:2}"
        ;;
	"notify")
		steps=($(cat $current_level_file))
		notify ${steps[0]} $(( ${#steps[@]} - 1 )) 
		;;
esac
