#!/bin/bash

# Скрипт для экспоненциального изменения яркости

# Предварительные танцы с бубном для решения проблемы с падающей яркостью тут:
# https://forums.linuxmint.com/viewtopic.php?t=138760

# Для работы выполнить от root'а следующую комманду (и добавить соответствующему файлу возможность исполнения)
# echo -e '#!/bin/bash\necho $1 >  [путь к файлу "brightness_file"]' > /usr/local/bin/brightness
# После чего прописать в /etc/sudoers строку:
# [Ваш логин] ALL = NOPASSWD: /usr/local/bin/brightness

current_level_file="/tmp/brightness_levels"
brightness_file="/sys/class/backlight/amdgpu_bl0/brightness"
max_brightness=255
min_brightness=0

notify_title=""
notify_body=""
notify_id=$(cat "$(dirname -- "$0")/notify-ids" | grep -oP "${0##*/} \K([\d]+)")

# Получить текущую яркость, возвращает число от 0 до 255
get() {
    cat $brightness_file
}

# Установить текущую яркость, аргументы: число от 0 до 255
set() {
    sudo brightness $1
}

# Увеличить яркость на один шаг
inc() {
    steps=($(cat $current_level_file))
    [[ ${steps[0]} -lt $(( ${#steps[@]} - 1 )) ]] && steps[0]=$(( ${steps[0]} + 1 ))
    echo ${steps[@]} > $current_level_file
    set ${steps[${steps[0]}]}
}

# Уменьшить яркость на один шаг
dec() {
    steps=($(cat $current_level_file))
    [[ ${steps[0]} -gt 1 ]] && steps[0]=$(( ${steps[0]} - 1 ))
    echo ${steps[@]} > $current_level_file
    set ${steps[${steps[0]}]}
}

# Установить количество шагов, аргументы: целое положительное число (в разумных пределах, т.е. до 255)
levels() {
    steps=($(python - << EOF
import sys
steps = $1 - 1
step = 256 ** (1 / steps)
levels = [0]
for n in range(steps):
    level = round(step ** (n + 1)) - 1
    level += max(0, levels[-1] - level + 1)
    levels.append(min(level, 255))
print(' '.join(map(str, levels[:256])))
EOF
    ))

    steps=(${#steps[@]} ${steps[@]})
    echo ${steps[@]} > $current_level_file
    set ${steps[${steps[0]}]}
}

# Создание дефолтного файла-конфигурации с 8 шагами
[[ ! -f $current_level_file ]] && levels 8

case $1 in
    "get")
        get
        ;;
    "set")
        set "${@:2}"
        ;;
    "inc")
        inc
        ;;
    "dec")
        dec
        ;;
    "levels")
        levels "${@:2}"
        ;;
esac
