#!/bin/bash

set -e

conf_path="$HOME/.i3/scripts/.xkb"
layouts_list_file="$conf_path/layouts_list"

notify_title="Раскладка клавиатуры"
notify_body="Текущая раскладка: "
notify_id=1020

set() {
    layouts=($@)

    printf "%s\n" "${layouts[@]}" > $layouts_list_file

    layout=""
    variant=""

    for i in ${layouts[@]}; do
        i=(${i//:/ })
        layout="$layout,${i[0]}"
        variant="$variant,${i[1]}"
    done

    layout=${layout:1}
    variant=${variant:1}

    setxkbmap -layout "$layout" -variant "$variant"
}

get_layout_list() {
    layout=$(tr '\n'  ' ' < $layouts_list_file)
    echo $layout
}

get_layout() {
    layout=$(setxkbmap -query | grep -oP 'layout:\s*\K([\w,]+)')
    echo $layout
}

get_CapsLock() {
    CapsLock=$(xset q | grep -oP 'Caps Lock:\s{0,}\K([\w]+)')
    echo $CapsLock
}

get_color() {
    current_CapsLock=$(get_CapsLock)
    if [[ $current_CapsLock = "on" ]]; then
        color=$(grep -oP 'color_bad\s=\s"\K(.{7})' "/etc/i3status.conf")
    else
        color=$(grep -oP 'color_good\s=\s"\K(.{7})' "/etc/i3status.conf")
    fi
    color="\"color\":\"$color\","
    echo $color
}

get() {
    current_layout=$(get_layout)
    current_layout=${current_layout:0:2}
    current_layout=${current_layout^^}
    current_CapsLock=$(get_CapsLock)
    current_CapsLock=${current_CapsLock//on/}
    current_CapsLock=${current_CapsLock//off/}
    block="$current_CapsLock $current_layout"
    echo $block
}

i3status() {
	while :
    do
    	read line
    	layout=$(get)
    	current_color=$(get_color)
    	block="{\"name\":\"Keyboard Layout\",$current_color\"markup\":\"none\",\"full_text\":\" $layout \",\"align\":\"center\",\"min_width\":70}"
    	echo "${line/\[\{/\[$block,\{}" || exit 1
    done
}

polybar() {
    current_CapsLock=$(get_CapsLock)
    if [[ $current_CapsLock = "on" ]]; then
        block="%{B#F0A080 F#404040}  %{B#444240 F#D0D0D0}"
    else
        block="%{B#A0A0C0 F#404040}  %{B#444240 F#D0D0D0}"
    fi

    current_layout=$(get_layout)
    current_layout=${current_layout:0:2}
    current_layout=${current_layout^^}
    block="$block $current_layout %{B- F-}"

    echo $block
}

toggle() {
    layouts=($(get_layout_list))

    layouts=(${layouts[@]:1} ${layouts[0]})

    printf "%s\n" "${layouts[@]}" > $layouts_list_file

    layout=""
    variant=""

    for i in ${layouts[@]}; do
        i=(${i//:/ })
        layout="$layout,${i[0]}"
        variant="$variant,${i[1]}"
    done

    layout=${layout:1}
    variant=${variant:1}

    setxkbmap -layout "$layout" -variant "$variant"

    current_layout=${layouts[0]}
    current_layout=${current_layout^^}
    current_layout=${current_layout//:/ в варианте }
    notify-send -a thunar -u low -r $notify_id "$notify_title" "$notify_body$current_layout"
}

case $1 in
    "set")
        set "${@:2}"
        ;;
    "get")
        get
        ;;
    "i3status")
        i3status
        ;;
    "polybar")
        polybar
        ;;
    "toggle")
        toggle
        ;;
esac
