#!/bin/bash

# Скрипт изменения раскладки клавиатуры

layouts_file="/tmp/keyboard-layouts"

notify_title="Раскладка клавиатуры"
notify_body="Текущая раскладка: "
notify_id=$(cat "$(dirname -- "$0")/notify-ids" | grep -oP "${0##*/} \K([\d]+)")

# Установка списка раскладок и их вариантов, аругменты: раскладка1[:вариант1] [раскладка2[:вариант2]] ...
set() {
    layouts=($@)
    echo ${layouts[@]} > $layouts_file

    layout=""
    variant=""

    for i in ${layouts[@]}; do
        i=(${i//:/ })
        layout="$layout,${i[0]}"
        variant="$variant,${i[1]}"
    done

    layout=${layout:1}
    variant=${variant:1}

    setxkbmap -layout "$layout" -variant "$variant" -option
}

# Возвращает список всех установленных раскладок в текущем смещении
get_layout_list() {
    cat $layouts_file
}

# Получение текущей установленной расскладки в сиситеме, возвращает буквенный индекс раскладки
get_layout() {
    layout=$(setxkbmap -query | grep -oP 'layout:\s*\K([\w,]+)')
    echo $layout
}

# Получение состояния капслока, возвращает on или off
get_CapsLock() {
    CapsLock=$(xset q | grep -oP 'Caps Lock:\s{0,}\K([\w]+)')
    echo $CapsLock
}

# Получение "цветов оповещения", установленных для i3status
get_color() {
    current_CapsLock=$(get_CapsLock)
    if [[ $current_CapsLock = "on" ]]; then
        color=$(grep -oP 'color_bad\s=\s"\K(.{7})' "/etc/i3status.conf")
    else
        color=$(grep -oP 'color_good\s=\s"\K(.{7})' "/etc/i3status.conf")
    fi
    color="\"color\":\"$color\","
    echo $color
}

# возвращает текущие данные о раскладке и состоянии капслока
get() {
    current_layout=$(get_layout)
    current_layout=${current_layout:0:2}
    current_layout=${current_layout^^}
    current_CapsLock=$(get_CapsLock)
    current_CapsLock=${current_CapsLock//on/}
    current_CapsLock=${current_CapsLock//off/}
    block="$current_CapsLock $current_layout"
    echo $block
}

# Возвращает блок для встраивания в i3status
i3status() {
	while :
    do
    	read line
    	layout=$(get)
    	current_color=$(get_color)
    	block="{\"name\":\"Keyboard Layout\",$current_color\"markup\":\"none\",\"full_text\":\" $layout \",\"align\":\"center\",\"min_width\":70}"
    	echo "${line/\[\{/\[$block,\{}" || exit 1
    done
}

# Возвращает блок для встраивания в polybar (завязано на моём текущем конфиге, не обессудьте, как-нибудь, но мои руки и до сюда доберутся)
polybar() {
    icon=($1)
    color=($2)

    current_CapsLock=$(get_CapsLock)
    if [[ $current_CapsLock = "on" ]]; then
        block="%{B${color[3]} F${color[0]}} ${icon[0]} %{B${color[1]} F${color[2]}}"
    else
        block="%{B${color[4]} F${color[0]}} ${icon[1]} %{B${color[1]} F${color[2]}}"
    fi

    current_layout=$(get_layout)
    current_layout=${current_layout:0:2}
    current_layout=${current_layout^^}
    block="$block $current_layout %{B- F-}"

    echo $block
}

# Переключение раскладки (смещение влево списка раскладок)
toggle() {
    layouts=($(get_layout_list))
    layouts=(${layouts[@]:1} ${layouts[0]})
    echo "${layouts[@]}" > $layouts_file

    for i in ${layouts[@]}; do
        i=(${i//:/ })
        layout="$layout,${i[0]}"
        variant="$variant,${i[1]}"
    done

    layout=${layout:1}
    variant=${variant:1}

    setxkbmap -layout "$layout" -variant "$variant" -option

    current_layout=${layouts[0]}
    current_layout=${current_layout^^}
    current_layout=${current_layout//:/ в варианте }
    notify-send -a thunar -u low -r $notify_id "$notify_title" "$notify_body$current_layout"
}

case $1 in
    "set")
        set "${@:2}"
        ;;
    "get")
        get
        ;;
    "i3status")
        i3status
        ;;
    "polybar")
        polybar "${@:2}"
        ;;
    "toggle")
        toggle
        ;;
esac
