#!/bin/bash

# Скрипт для оповещения о низком заряде аккумулятора устройства
# Аругменты: пороговое_значение1:время_опрашивания_до_порогового_значения_1 [пороговое_значение2:время_опрашивания_до_порогового_значения_2] ...

bat_file="/sys/class/power_supply/BAT1/uevent"

plug="---"

notify_title="Низкий заряд батареи!"
notify_body="Осталось $plug% заряда, устройство следует подключить к источнику питания"
notify_id=$(cat "$(dirname -- "$0")/notify-ids" | grep -oP "${0##*/} \K([\d]+)")

alert_time=5s
sleep_time=0

get_state() {
    echo $(grep -oP "POWER_SUPPLY_$1=\K(.+)" $bat_file)
}

level_setups=(${@:1})
notify_level=${1//:*/}

while :
do
    bat_capacity=$(get_state CAPACITY)
    bat_status=$(get_state STATUS)

    sleep_time=$alert_time
    for setup in ${level_setups[@]}; do
        setup=(${setup//:/ })
        [[ $bat_capacity -ge ${setup[0]} ]] && sleep_time=${setup[1]} && break
    done

    [[ $bat_status == "Discharging" ]] && [[ $bat_capacity -lt $notify_level ]] &&  echo "$notify_title" && notify-send -u critical -r $notify_id "$notify_title" "${notify_body//$plug/$bat_capacity}"

    sleep $sleep_time
done
