#!/bin/bash

notify_title="Закон против транслюдей 🏳️‍⚧️"
notify_body="Дней с принятия закона против существования трансгендерных людей: "
notify_icon="dialog-error"
notify_urgent="normal"

notify_name="${0##*/}"
notify_id=$(cat "$HOME/.local/scripts/notify-ids" | grep -oP "$notify_name \K([\d]+)" || echo 0)

days_from()
{
    echo $(( ($(date +%s) - $(date -d $1 +%s)) / (60 * 60 * 24) ))
}

antiTRANSlaw_date=20230724

days=$(days_from $antiTRANSlaw_date)

notify-send -a "$notify_name" -r "$notify_id" -u "$notify_urgent" -i "$notify_icon" "$notify_title" "$notify_body$days"
