#!/bin/bash

pb_colors_file="$HOME/.config/polybar/colors.ini"
icons=("" "")

set() {
    dunstctl set-paused $1
	polybar-msg action notify-mute hook 0
}

is-muted() {
    [[ $(dunstctl is-paused) == "true" ]]
}

polybar() {
    iprfx=${icons[0]}
    iprfxa=${icons[1]}

    bg=$(grep -oP "background =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file)
    fga=$(grep -oP "foreground-alt =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file)
    prfx=$(grep -oP "blue =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file)
    prfxa=$(grep -oP "red =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file)

    if is-muted; then
        block="%{B$prfxa F$fga} $iprfxa %{B- F-}"
    else
        block="%{B$prfx F$fga} $iprfx %{B- F-}"
    fi

	block="%{u$bg o$bg}%{+u +o}%{A1:$1 toggle:}$block%{A}%{u- o-}"

    echo $block
}

case $1 in
    "mute")
        set true
        ;;
    "unmute")
        set false
        ;;
    "toggle")
        set toggle
        ;;
    "muted")
        is-muted
        ;;
    "polybar")
        polybar "$0"
        ;;
esac
