#!/bin/bash

player_status=$(playerctl status 2>/dev/null)
metadata=""
if [[ $? -eq 0 ]] && [[ $player_status != "Stopped" ]]; then
    artist=$(playerctl metadata artist 2>/dev/null)
    title=$(playerctl metadata title 2>/dev/null)
    metadata="$artist — $title"
fi

metadata() {
    case $player_status in
        "Playing") echo "%{F#D0D0D0}$metadata%{F-}" ;;
        "Paused") echo "%{F#808080}$metadata%{F-}" ;;
        *) echo "" ;;
    esac
}

playpause() {
    case $player_status in
        "Playing") echo "%{F#D0D0D0}%{F-}" ;;
        "Paused") echo "%{F#D0D0D0}%{F-}" ;;
        "Stopped") echo "%{F#808080}%{F-}" ;;
        *) echo "" ;;
    esac
}

prev() {
    case $player_status in
        "Playing" | "Paused") echo "%{F#D0D0D0}%{F-}" ;;
        "Stopped") echo "%{F#808080}%{F-}" ;;
        *) echo "" ;;
    esac
}

next() {
    case $player_status in
        "Playing" | "Paused") echo "%{F#D0D0D0}%{F-}" ;;
        "Stopped") echo "%{F#808080}%{F-}" ;;
        *) echo "" ;;
    esac
}

case $1 in
    "metadata")
        metadata
        ;;
    "playpause")
        playpause
        ;;
    "prev")
        prev
        ;;
    "next")
        next
        ;;
esac
