#!/bin/bash

current_md_file="/tmp/player-metadata"
pb_colors_file="$HOME/.config/polybar/colors.ini"
pb_icon=""
pb_line_length=40

notify_title=""
notify_title_default="Сейчас воспроизводится"
notify_body=""
notify_icon="applications-multimedia"
notify_urgent="low"

notify_name="${0##*/}"
notify_id=$(cat "$HOME/.local/scripts/notify-ids" | grep -oP "$notify_name \K([\d]+)" || echo 0)

stop-daemon() {
	process_name=${0##*/}
	for pid in $(pgrep ${process_name}) ; do
		[ $pid != $$ ] && kill -s KILL -- $pid && echo "Процесс $process_name $pid был остановлен"
	done
}

daemon() {
	stop-daemon
	
	md_raw_old=()
	status_old=""
	
	while :; do
		status="$(status)"
		IFS=$'\n' md_raw=($(metadata))
		if [[ "${md_raw[@]}" != ${md_raw_old[@]} ]] ; then
			md_raw_old=(${md_raw[@]})
			notify
			update-polybar
		elif [[ "$status" != "$status_old" ]] ; then
			status_old="$status"
			update-polybar
		fi
		sleep 1s
	done &
}

update-polybar() {
	polybar-msg action player hook 0 > /dev/null
}

control() {
	playerctl $1
	update-polybar
}

status() {
	playerctl status 2>/dev/null || echo ""
}

metadata() {
	playerctl metadata artist 2>/dev/null || echo ""
	playerctl metadata title 2>/dev/null || echo ""
}

field() {
	case "$1" in
        "Playing")     echo "%{F$4}$2%{F-}" ;;
        "Paused" )     echo "%{F$5}$3%{F-}" ;;
        "Stopped")     echo "%{F$6}$3%{F-}" ;;
        *) echo "" ;;
    esac
}

get_pb_color() {
	color=()
	color+=($(grep -oP "background =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))
	color+=($(grep -oP "background-alt =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))
	color+=($(grep -oP "foreground =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))
	color+=($(grep -oP "foreground-alt =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))
	color+=($(grep -oP "foreground-inactive =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))
	color+=($(grep -oP "blue =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))

	echo "${color[@]}"
}

polybar() {
	color=($(get_pb_color))
	bg=${color[0]}
	bga=${color[1]}
	fg=${color[2]}
	fga=${color[3]}
	fgi=${color[4]}
	prfx=${color[5]}

	IFS=$'\n' md_raw=($(metadata))
	status="$(status)"

	if [[ -z "${md_raw[0]}" ]] && [[ -z "${md_raw[1]}" ]] ; then return 0
	elif [[ -n "${md_raw[0]}" ]] && [[ -n "${md_raw[1]}" ]] ; then md="${md_raw[0]} ─ ${md_raw[1]}" 
	else md="${md_raw[@]}"
	fi
	[[ ${#md} -gt $(( $pb_line_length + 3 )) ]] && md="${md::$pb_line_length}..."

	icon="%{B$prfx F$fga}%{A1:$1 -n:} $pb_icon %{A}%{B- F-}"
	
	line="%{B$bga F$fga}"
	line="$line %{A1:$1 -c previous:}$(field "$status" "" "" "$fg" "$fg" "$fgi")%{A}"
    line="$line %{A1:$1 -c play-pause:}$(field "$status" "" "" "$fg" "$fg" "$fgi")%{A}"
    line="$line %{A1:$1 -c next:}$(field "$status" "" "" "$fg" "$fg" "$fgi")%{A}"
    line="$line %{A1:$1 -c play-pause:}$(field "$status" "$md" "$md" "$fg" "$fgi" "$fgi")%{A}"
	line="$line %{B- F-}"

	block="%{u$bg o$bg}%{+u}%{+o}$icon$line%{u- o-}"

	case "$(status)" in
		"Playing" | "Paused" | "Stopped") echo $block ;;
		*) echo "" ;;
	esac
}

notify() {
	IFS=$'\n' md_raw=($(metadata))

	if [[ -z "${md_raw[@]}" ]] ; then return 0
	elif [[ -z "${md_raw[0]}" ]] ; then
		notify_title="$notify_title_default"
		notify_body="${md_raw[1]}"
	elif [[ -z "${md_raw[1]}" ]] ; then 
		notify_title="$notify_title_default"
		notify_body="${md_raw[0]}"
	else
		notify_title="${md_raw[0]}"
		notify_body="${md_raw[1]}"
	fi

	notify-send -a "$notify_name" -r "$notify_id" -u "$notify_urgent" -i "$notify_icon" "$notify_title" "$notify_body"
}

help() {
	echo "Help is coming coon!"
}

if [[ $# -eq 0 ]] ; then help ; exit 0 ; fi

while [[ $# -gt 0 ]] ; do
	case $1 in
		"-c" | "--control")
			grep -oP '^play$|^pause$|^play-pause$|^stop$|^previous$|^next$' <<< "$2" > /dev/null && \
				control $2 && shift
			status
			;;
		"-m" | "--metadata")
			metadata
			;;
    	"-p" | "--polybar")
        	polybar "$0"
        	;;
		"-u" | "--update")
			update-polybar
			;;
		"-n" | "--notify")
			notify
			;;
		"-h" | "--help")
			help
			;;
		"--stop-daemon")
			stop-daemon
			;;
		"--daemon")
			daemon
			;;
		*)
			echo "Ошибка! Неизвестный аругмент $1."
            exit 1
            ;;
	esac

	shift
done

