#!/bin/bash

shortname="tray"
barname="polybar-$shortname"
conffile="$HOME/.config/i3/polybar/config"
pid=""

start() {
    while pgrep -f "$barname " > /dev/null; do sleep 1; done
    exec -a $barname polybar -q -c $conffile $shortname
}

expand() {
    polybar-msg -p "$pid" cmd show
}

collapse() {
    polybar-msg -p "$pid" cmd hide
}

toggle() {
    polybar-msg -p "$pid" cmd toggle
}

pgrep -f "$barname " > /dev/null || start
pid=$(pgrep -f "$barname ")

case $1 in
    "expand")
        expand
    ;;
    "collapse")
        collapse
    ;;
    "toggle")
        toggle
    ;;
esac
