#!/bin/bash

update_script="$HOME/.config/i3/scripts/update"
confirm_script="$HOME/.config/i3/scripts/confirm"
conffile="$HOME/.config/i3/rofi/powermenu.rasi"


# uptime=$(uptime -p | sed -e 's/up //g')
uptime=$(uptime -p | sed -e 's/up //g' | sed -e 's/ h[a-z]*\,\ /:/g' | sed -e 's/m[a-z]*//g')

confirm_hibernate=("Перевести систему в гибернацию?" " Перевести в сон" " Отмена")
confirm_logout=("Выйти из системы?" " Выйти" " Отмена")
confirm_reboot=("Перезагрузить компьютер?" " Перезагрузить" " Отмена")
confirm_shutdown=("Выключить компьютер?" " Выключить" " Отмена")
confirm_update=("Обновить и выключить компьютер?" " Обновить и выключить" " Отмена")


# Confirmation
confirm() {
    $("$confirm_script" "$1" "$2" "$3") && eval $4 || exit 0
}

# Options
lock=" Заблокировать"
hibernate=" Сохранить состояние"
logout=" Выйти"
reboot=" Перезагрузить"
shutdown=" Завершить работу"
update=" Обновить и завершить работу"

# Variable passed to rofi
options="$lock\n$hibernate\n$logout\n$reboot\n$shutdown\n$update"

chosen="$(echo -e "$options" | rofi -no-config -no-lazy-grab -dmenu -p "Uptime: $uptime" -theme $conffile)"


case $chosen in
    $lock)
        dm-tool lock
        ;;
    $hibernate)
        confirm "${confirm_hibernate[@]}" "systemctl hibernate"
        ;;
    $logout)
        confirm "${confirm_logout[@]}" "i3-msg exit"
        ;;
    $reboot)
        confirm "${confirm_reboot[@]}" "systemctl reboot"
        ;;
    $shutdown)
        confirm "${confirm_shutdown[@]}" "systemctl poweroff"
        ;;
    $update)
        confirm "${confirm_update[@]}" "$update_script \"systemctl poweroff\""
        ;;
esac
