#!/bin/bash

powermenu_script="$HOME/.local/scripts/powermenu"
update_script="$HOME/.local/scripts/update -t kitty"
confirm_script="$HOME/.local/scripts/confirm"
themefile="$HOME/.config/rofi/powermenu.rasi"

lock_icon="\0icon\x1fsystem-lock-screen-symbolic"
hibernate_icon="\0icon\x1fdocument-save"
logout_icon="\0icon\x1fsystem-log-out-symbolic"
reboot_icon="\0icon\x1fsystem-reboot-symbolic"
shutdown_icon="\0icon\x1fsystem-shutdown-symbolic"
update_icon="\0icon\x1fsoftware-update-available-symbolic"
cancel_icon="\0icon\x1fedit-undo-symbolic"

lock="Заблокировать"
hibernate="Сохранить состояние"
logout="Выйти"
reboot="Перезагрузить"
shutdown="Завершить работу"
update="Обновить и выключить"
cancel="Отмена"

hibernate_title="Перевести систему в гибернацию?"
logout_title="Выйти из системы?"
reboot_title="Перезагрузить компьютер?"
shutdown_title="Выключить компьютер?"
update_title="Обновить и завершить работу?"

uptime=$(uptime -p | sed -e 's/up //g' | sed -e 's/ h[a-z]*\,\ /:/g' | sed -e 's/m[a-z]*//g')

confirm_hibernate=( "$hibernate_title" "$hibernate" "$hibernate_icon" "$cancel" "$cancel_icon" )
confirm_logout=(    "$logout_title"    "$logout"    "$logout_icon"    "$cancel" "$cancel_icon" )
confirm_reboot=(    "$reboot_title"    "$reboot"    "$reboot_icon"    "$cancel" "$cancel_icon" )
confirm_shutdown=(  "$shutdown_title"  "$shutdown"  "$shutdown_icon"  "$cancel" "$cancel_icon" )
confirm_update=(    "$update_title"    "$update"    "$update_icon"    "$cancel" "$cancel_icon" )

confirm() {
    $("$confirm_script" "$1" "$2" "$3" "$4" "$5") && eval $6 || exit 0
}

options="$lock$lock_icon
$hibernate$hibernate_icon
$logout$logout_icon
$reboot$reboot_icon
$shutdown$shutdown_icon
$update$update_icon"

chosen=$(echo -e "$options" | rofi -no-config -no-lazy-grab -dmenu -show-icons -p "В работе: $uptime" -theme $themefile)

case $chosen in
    $lock)
        dm-tool lock
        ;;
    $hibernate)
        confirm "${confirm_hibernate[@]}" "loginctl hibernate"
        ;;
    $logout)
        confirm "${confirm_logout[@]}" "i3-msg exit"
        ;;
    $reboot)
        confirm "${confirm_reboot[@]}" "loginctl reboot"
        ;;
    $shutdown)
        confirm "${confirm_shutdown[@]}" "loginctl poweroff"
        ;;
    $update)
        confirm "${confirm_update[@]}" "$update_script -c \"loginctl poweroff\""
        ;;
esac
