#!/bin/bash

terminal="exo-open --launch TerminalEmulator"

notify_title="Обнавление системы"
notify_body="Все обновления системы были завершены успешно."
notify_body_error="Обнаружено несколько ошибок - "
notify_icon="update-low"
notify_icon_error="update-high"
notify_id=$(cat "$(dirname "$0")/notify-ids" | grep -oP "${0##*/} \K([\d]+)")

log_file="/tmp/update-log"

log_sfx=" 2>> $log_file ; echo \$? >> $log_file ; "

command1="/usr/bin/dnf upgrade --refresh -y $log_sfx"
command2="/usr/bin/flatpak update -y $log_sfx"
command3="/sbin/btrfs balance start -v -dusage=1 / $log_sfx"
command4="$(dirname "$0")/${0##*/} -n $USER ; echo -e '\a' ; "
command5="/usr/bin/read -t 120 -p \"Для выхода нажмите ENTER (в противном случае программа сама завершится через 2 минуты)\" ; "
command6="echo ''"

command_line="$command1 $command2 $command3 $command4 $command5 $command6"

check() {
    [ ! -f $log_file ] && exit 1
    errors_count=$(($(grep "^[1-9][0-9]*$" /tmp/update-log | wc -l)))
    if [[ errors_count -eq 0 ]]; then
        sudo -H -u $1 notify-send -u normal -r $notify_id -i "$notify_icon" "$notify_title" "$notify_body"
        exit 0
    fi
    errors=$(grep "^[^0-9].*$" $log_file)
    notify_body_error="$notify_body_error$errors_count:\n$errors"
    sudo -H -u $1 notify-send -u critical -r $notify_id -i "$notify_icon_error" "$notify_title" "$notify_body_error"
}

update() {
    rm $log_file 2> /dev/null ; touch $log_file
    pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY PATH=$PATH $terminal /bin/bash -c "$command_line"
    wait
}

help() {
echo -e "Скрипт для упрощения применения обновлений системы.\n"
    echo -e "\t-t\t--terminal <name>\tИспользование конкретного эмулятора терминала\n\t\t\t\t\tвместо оного по-умолчанию.\n"
    echo -e "\t-c\t--command <name>\tДобавление произвольной команды в конец сценария.\n"
    echo -e "\t-n\t--notify <user>\t\tПроверка успешности обновлений и вывод\n\t\t\t\t\tуведомления о завершении стандартного сценария\n\t\t\t\t\t(вызывается автоматически).\n"
    echo -e "\t-s\t--script\t\tВывод списка команд сценария.\n"
    echo -e "\t-h\t--help\t\t\tВывод данной справки.\n"
}

script() {
    echo -e "Список команд сценария:\n"
    echo -e "\t1. $command1\n"
    echo -e "\t2. $command2\n"
    echo -e "\t3. $command3\n"
    echo -e "\t4. $command4\n"
    echo -e "\t5. $command5\n"
}

while [[ $# -gt 0 ]] ; do
    case $1 in
        "-t" | "--terminal")
            terminal=$2
            shift
            ;;
        "-c" | "--command")
            command6=$2
            shift
            ;;
        "-s" | "--script")
            script
            exit 0
            ;;
        "-h" | "--help")
            help
            exit 0
            ;;
        "-n" | "--notify")
            check $2
            exit 0
            ;;
        *)
            echo "Ошибка! Неизвестный аругмент $1."
            exit 1
            ;;
    esac

    shift
done

update

