#!/bin/bash

# Скрипт для изменения громкости, шоб ~*~*~красивое~*~*~ было

current_level_file="/tmp/volume-levels"
pb_modules_file="$HOME/.config/polybar/modules.ini"
pb_colors_file="$HOME/.config/polybar/colors.ini"
pb_icons=("" "" "" "")
pb_steps=10

notify_title="Громкость"
notify_body="Текущая громкость системы"
notify_body_muted="Звук отключен"
notify_icons=("audio-volume-muted" "audio-volume-low" "audio-volume-medium" "audio-volume-high")
notify_urgent="low"

notify_name="${0##*/}"
notify_id=$(cat "$HOME/.local/scripts/notify-ids" | grep -oP "$notify_name \K([\d]+)" || echo 0)

daemon="no"

# Создание дефолтного файла-конфигурации, если оный отсутствует
check_levels_file()
{
	[[ ! -f $current_level_file ]] && setup default
}

# Принудительное обновление полибара
update() {
	polybar-msg action volume hook 0 > /dev/null
}

# Получить текущую громкость, возвращает целое число - громкость в процентах
get_volume() {
	levels=( $( pactl get-sink-volume @DEFAULT_SINK@ 2>/dev/null | grep -oP "[\w\p{P}]+\s+\K([\d]+%\s)" | grep -oP "\d+" ) ) || exit 1

	echo $(( ( ${levels[0]} + ${levels[1]} ) / 2 ))
	
	check_levels_file

	steps=($(cat $current_level_file))
	if [[ ${steps[${steps[0]}]} -ne $levels ]] ; then
		level=0
		for i in ${steps[@]:1} ; do
			(( level++ ))
			if [[ $i -ge $levels ]] ; then
				steps[0]=$level
				break
			fi
		done
	echo ${steps[@]} > $current_level_file &
	fi
}

# ПОучить состояние режима без звука
get_mute() {
	mute=$(pactl get-sink-mute @DEFAULT_SINK@ 2>/dev/null | grep -oP "\w*: \K(\w+)") || exit 1
	echo $mute
}

# Установить текущую яркость, аргументы: целое число - громкость в процентах
set_volume() {
	pactl set-sink-mute @DEFAULT_SINK@ false 2>/dev/null || exit 1
	pactl set-sink-volume @DEFAULT_SINK@ $1% 2>/dev/null || exit 1
	notify $1
}

# Установить режим без звука (аргументы ангалогичны соответствующему действию в pactl, по умолчанию переключает режим)
set_mute() {
	p=$1
	[[ ${#p} -eq 0 ]] && p="toggle"
	pactl set-sink-mute @DEFAULT_SINK@ $p 2>/dev/null || exit 1
	notify $(get_volume)
}

# Увеличить яркость на один шаг
inc() {
	check_levels_file
	steps=($(cat $current_level_file))
	[[ ${steps[0]} -lt $(( ${#steps[@]} - 1 )) ]] && steps[0]=$(( ${steps[0]} + 1 ))
	set_volume ${steps[${steps[0]}]}
	echo ${steps[@]} > $current_level_file &
}

# Уменьшить яркость на один шаг
dec() {
	check_levels_file
	steps=($(cat $current_level_file))
	[[ ${steps[0]} -gt 1 ]] && steps[0]=$(( ${steps[0]} - 1 ))
	set_volume ${steps[${steps[0]}]}
	echo ${steps[@]} > $current_level_file &
}

get_pb_color() {
	color=()
	color=(${color[@]} $(grep -oP "background =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))
	color=(${color[@]} $(grep -oP "background-alt =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))
	color=(${color[@]} $(grep -oP "foreground =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))
	color=(${color[@]} $(grep -oP "foreground-alt =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))
	color=(${color[@]} $(grep -oP "foreground-inactive =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))
	color=(${color[@]} $(grep -oP "blue =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))
	color=(${color[@]} $(grep -oP "red =\s*\K(#[a-fA-F0-9]+)" $pb_colors_file))

	echo ${color[@]}
}

get_pb_bar() {
	bar=()
	bar=(${bar[@]} $(grep -oP "^fill\s*=\s*\K([^\n]+)$" $pb_modules_file))
	bar=(${bar[@]} $(grep -oP "^indicator\s*=\s*\K([^\n]+)$" $pb_modules_file))
	bar=(${bar[@]} $(grep -oP "^empty\s*=\s*\K([^\n]+)$" $pb_modules_file))

	echo ${bar[@]}
}

polybar() {
	color=($(get_pb_color))
	bg=${color[0]}
	bga=${color[1]}
	fg=${color[2]}
	fga=${color[3]}
	fgi=${color[4]}
	fgu=${color[6]}
	prfx=${color[5]}
	prfxa=${color[6]}

	bar=($(get_pb_bar))
	fill=${bar[0]}
	indicator=${bar[1]}
	empty=${bar[2]}

	volume=$(get_volume)
	mute=$(get_mute)

	pb_icon="%{B$prfx F$fga} ${pb_icons[3]} %{B- F-}"
	[[ $volume -lt 70 ]] && pb_icon="%{B$prfx F$fga} ${pb_icons[2]} %{B- F-}"
	[[ $volume -lt 40 ]] && pb_icon="%{B$prfx F$fga} ${pb_icons[1]} %{B- F-}"
	[[ $volume -lt 5  ]] && pb_icon="%{B$prfxa F$fga} ${pb_icons[0]} %{B- F-}"
	[[ $mute == "yes"  ]] && pb_icon="%{B$prfxa F$fga} ${pb_icons[0]} %{B- F-}"

	bar="%{B$bga} "
	if [[ $mute == "yes" ]] ; then
		bar="$bar%{F$fg}Без звука!%{F-}"
	else
		pos=$(( (volume + pb_steps / 2) / pb_steps ))
		opos=$(( pos - pb_steps ))
		for i in $(seq 1 $pb_steps) ; do
			el=""
			[[ $i -gt $pos ]] && el="%{F$fgi}$empty%{F-}"
			[[ $i -eq $pos ]] && el="%{F$fg}$indicator%{F-}"
			[[ $i -lt $pos ]] && el="%{F$fg}$fill%{F-}"
			[[ $i -eq $opos ]] && el="%{F$fgu}$fill%{F-}"
			[[ $i -lt $opos ]] && el="%{F$fgu}$fill%{F-}"

			bar="$bar$el"
		done
	fi

	block="%{u$bg o$bg}%{+u}%{+o}%{A1:$1 -m toggle:}$pb_icon%{A}%{A4:$1 +:}%{A5:$1 -:}$bar %{B- F-}%{A}%{A}%{u- o-}"
	echo $block
}

# Послать уведомление об изменении громкости
notify() {
	update

	mute=$(get_mute)

	if [[ $mute == "yes" ]] ; then
		notify_icon="${notify_icons[0]}"
		notify-send -a "$notify_name" -r "$notify_id" -u "$notify_urgent" -i "$notify_icon" "$notify_title" "$notify_body_muted"
	else
		notify_icon="${notify_icons[3]}"
		[[ $1 -lt 70 ]] && notify_icon="${notify_icons[2]}"
		[[ $1 -lt 40 ]] && notify_icon="${notify_icons[1]}"
		[[ $1 -lt 5  ]] && notify_icon="${notify_icons[0]}"
		notify-send -a "$notify_name" -r "$notify_id" -u "$notify_urgent" -i "$notify_icon" "$notify_title" "$notify_body" -h int:value:$1
	fi
}

# Установить количество шагов, аргументы: два целых неотрицательных числа - количество шагов от 0 до 100 (как минимум 1) и количество шагов свех 100 (может быть 0)
setup() {
	steps=($(python - << EOF
steps = $(( 1 + $(( $1 )) ))
upsteps = $(( 0 + $(( $2 )) ))
levels = list(map(lambda x: x * 100 // (steps - 1), range(steps + upsteps)))
print(' '.join(map(str, levels)))
EOF
	))

	steps=("0" ${steps[@]})
	echo ${steps[@]} > $current_level_file &
}

help() {
	echo -e "Скрипт для управления громкостью звуковой системы и вывода некоторых данных о её состоянии.\n"
	echo -e "\t-l\t--level\t\t\t[<number>]\n\t\tУстановить указанный уровень громкости (по умолчанию остаётся прежним)\n\t\tи вывести текущее значение.\n"
	echo -e "\t-m\t--mute\t\t\t[0|1|toggle]\n\t\tУстановить или переключить режим 'без звука' (по умолчанию остаётся прежним)\n\t\tи вывести текущее значение.\n"
	echo -e "\t-i\t--increment\t+\t[<number>]\n\t\tУвеличить громкость звука на заданное количество шагов (по умолчанию - на 1).\n"
	echo -e "\t-d\t--decrement\t-\t[<number>]\n\t\tУменьшить громкость звука на заданное количество шагов (по умолчанию - на 1).\n"
	echo -e "\t-s\t--setup\t\t\t[<number>[+<number>]|default]\n\t\tУстановить конфигурацию шагов изменения громкости в формате,\n\t\tгде сначала указывается количество шагов от 0% до 100%, а после,\n\t\tопционально, через знак '+' указывается количество шагов сверх 100%\n\t\tгромкости, либо же применение стандартной конфигурации\n\t\t(10 шагов от 0% до 100%), по умолчанию - оставить прежнюю\n\t\tконфигурацию; и вывести текущую конфигурацию.\n"
	echo -e "\t-p\t--polybar\n\t\tПолучить форматированный текст для модуля панели Polybar.\n"
	echo -e "\t-u\t--update\n\t\tПринудительно обновить соответствующий модуль панели Polybar.\n"
	echo -e "\t--daemon\n\t\tЗапустить фоновый цикл переодического обновления модуля панели Polybar.\n"
	echo -e "\t-h\t--help\n\t\tВывести данную справку.\n"
	echo -e "Автор: allonny89"
}

while [[ $# -gt 0 ]] ; do
	case $1 in
		"-l" | "--level")
			if echo $2 | grep -oP "^\d+$" > /dev/null ; then
				set_volume $2
				shift
			fi
			get_volume
			;;
		"-m" | "-mute")
			if echo $2 | grep -oP "^0$|^1$|^toggle$" > /dev/null ; then
				set_mute $2
				shift
			fi
			get_mute
			;;
		"-i" | "--increment" | "+")
			if echo $2 | grep -oP "^\d+$" > /dev/null ; then
				n=$(( $2 ))
				while [[ $n -gt 0 ]] ; do
					inc
					n=$(( $n - 1 ))
				done
				shift
			else
				inc
			fi
			;;
		"-d" | "--decrement" | "-")
			if echo $2 | grep -oP "^\d+$" > /dev/null ; then
				n=$(( $2 ))
				while [[ $n -gt 0 ]] ; do
					dec
					n=$(( $n - 1 ))
				done
				shift
			else
				dec
			fi	
			;;
		"-s" | "--setup")
			if echo $2 | grep -oP "^\d+(\+?\d+)?$" | grep -oP "\d+" > /dev/null ; then
				steps=$(echo $2 | grep -oP "^\d+(\+?\d+)?$" | grep -oP "\d+")
				setup $steps
				shift
			fi
			if echo $2 | grep -oP "^default$" > /dev/null ; then
				setup 10
				shift
			fi
			cat $current_level_file
			;;
		"-p" | "--polybar")
			polybar "$0"
			;;
		"-u" | "--update")
			update
			;;
		"-h" | "--help")
			help
			;;
		"--daemon")
			daemon="yes"
			;;
		*)
            echo "Ошибка! Неизвестный аругмент $1."
            exit 1
            ;;
	esac
    
	shift
done

if [[ $daemon == "yes" ]] ; then
	process_name=${0##*/}
	for pid in $(pgrep ${process_name}) ; do
		[ $pid != $$ ] && kill -s KILL -- $pid && echo "Процесс $process_name $pid был остановлен"
	done
	sleep 1s
	while :; do
		update
		sleep 5s
	done &
fi

