#!/bin/bash

notify_title="Подключение VPN"
notify_body_up="Соединение с VPN установлено."
notify_body_down="Соединение с VPN отключено."
#notify_icon="nm-vpn-standalone-lock"
notify_icon_up="network-connect"
notify_icon_down="network-disconnect"

notify_title_error="Ошибка VPN подключения"
notify_body_error=""
notify_icon_error="dialog-error"

notify_id=$(cat "$(dirname -- "$0")/notify-ids" | grep -oP "${0##*/} \K([\d]+)")

[[ -z $(nmcli -g ACTIVE connection show "$1") ]] && state="up" || state="down"
notify_body_error=$(nmcli -w 10 connection $state "$1" 2>&1)

if [[ $? -ne 0 ]] ; then
    echo $notify_body_error
    notify-send -u critical  -r $notify_id -i "$notify_icon_error" "$notify_title_error" "$notify_body_error"
    exit 1
fi

notify_icon="notify_icon_${state}"
notify_body="notify_body_${state}"
notify-send -u low -r $notify_id -i "${!notify_icon}" "$notify_title" "${!notify_body}"


